server:
  port: 8080

spring:
  application:
    name: mcs-scheduler
  grpc:
    server:
      port: 9090
  flyway:
    default-schema: public
  quartz:
    jdbc:
      initialize-schema: never

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      probes:
        enabled: true
